BEGIN TRANSACTION;
CREATE TABLE "episode" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`title`	TEXT NOT NULL,
	`pub_date`	TEXT NOT NULL,
	`url`	TEXT NOT NULL UNIQUE,
	`channel_id`	TEXT NOT NULL,
	`flg_feed`	NUMERIC NOT NULL DEFAULT 0
);
CREATE TABLE "channel" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	`url`	TEXT NOT NULL UNIQUE,
	`image_url`	TEXT NOT NULL
);
COMMIT;
